apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extensionlib.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{ if .Values.deploymentAnnotations }}
  annotations:
    {{- with .Values.deploymentAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- include "extensionlib.labels" (list .) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "extensionlib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "extensionlib.selectorLabels" . | nindent 8 }}
        {{- include "extensionlib.labels" (list .) | nindent 8 }}
        {{- range $key, $value := .Values.extraLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        oneagent.dynatrace.com/injection: "false"
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: extension
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            {{- if .Values.discovery.attributes.excludes.application }}
            - name: STEADYBIT_EXTENSION_DISCOVERY_ATTRIBUTES_EXCLUDES_APPLICATIONS
              value: {{ join "," .Values.discovery.attributes.excludes.application | quote }}
            {{- end }}
            {{- if .Values.discovery.attributes.excludes.healthRule }}
            - name: STEADYBIT_EXTENSION_DISCOVERY_ATTRIBUTES_EXCLUDES_HEALTH_RULES
              value: {{ join "," .Values.discovery.attributes.excludes.healthRule | quote }}
            {{- end }}
            {{- if .Values.appdynamics.accessToken }}
            - name: STEADYBIT_EXTENSION_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "appdynamics.secret.name" . }}
                  key: accessToken
            {{- end }}
            - name: STEADYBIT_EXTENSION_API_BASE_URL
              value: {{ .Values.appdynamics.apiBaseUrl | quote }}
            {{- if not .Values.appdynamics.accessToken }}
            - name: STEADYBIT_EXTENSION_API_CLIENT_NAME
              value: {{ .Values.appdynamics.apiClientName | quote }}
            - name: STEADYBIT_EXTENSION_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "appdynamics.secret.name" . }}
                  key: apiClientSecret
            - name: STEADYBIT_EXTENSION_ACCOUNT_NAME
              value: {{ .Values.appdynamics.accountName | quote }}
            {{- end }}
            {{- if .Values.appdynamics.eventApplicationID }}
            - name: STEADYBIT_EXTENSION_EVENT_APPLICATION_ID
              value: {{ .Values.appdynamics.eventApplicationID | quote }}
            {{- end }}
            {{- if .Values.appdynamics.actionSuppressionTimezone }}
            - name: STEADYBIT_EXTENSION_ACTION_SUPPRESSION_TIMEZONE
              value: {{ .Values.appdynamics.actionSuppressionTimezone | quote }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "extensionlib.deployment.volumeMounts" (list .) | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            httpGet:
              path: /health/liveness
              port: 8084
          readinessProbe:
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            httpGet:
              path: /health/readiness
              port: 8084
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- include "extensionlib.deployment.volumes" (list .) | nindent 8 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
