{{- if (and (not .Values.appdynamics.existingSecret) (or .Values.appdynamics.accessToken .Values.appdynamics.apiClientSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appdynamics.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  {{ if .Values.appdynamics.accessToken -}}
  accessToken: {{ .Values.appdynamics.accessToken | b64enc | quote }}
  {{- end }}
  {{ if .Values.appdynamics.apiClientSecret -}}
  apiClientSecret: {{ .Values.appdynamics.apiClientSecret| b64enc | quote }}
  {{- end }}
{{- end }}
