{{- if not .Values.appdynamics.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appdynamics.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  accessToken: {{ .Values.appdynamics.accessToken | b64enc | quote }}
  apiClientSecret: {{ .Values.appdynamics.apiClientSecret| b64enc | quote }}
{{- end }}
